name = "app"
version = "1.0.0"
target = "erlang"
gleam = ">= 1.1.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 1.2.0 and < 2.0.0"
mist = ">= 2.0.0 and < 3.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
gleam_erlang = ">= 0.27.0 and < 1.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
decode = ">= 0.3.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
